# Uncomment the next line to define a global platform for your project
platform :macos, '14.0'

target 'Handler 3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Writer
  pod 'RMQClient', '~> 0.12.0'

end